title: Hampton Morgan
author: Hampton Morgan
url: https://k4kfh.github.io # root address of the site
description: > # description of the site (multiple lines allowed)
  ...

permalink: /:slug

# Exclude backend files
exclude:
- README.md

#favicon: "./logo.png" # relative path to site's favicon

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user

  # Make the "Home" button an arrow, as the author did on their site: https://www.abhinav.co/blog
  back_home_text: '<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"></rect><circle cx="128" cy="128" r="96" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="12"></circle><polyline points="121.9 161.9 88 128 121.9 94.1" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></polyline><line x1="88" y1="128" x2="168" y2="128" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></line></svg>' # customize text for homepage link in post layout
  date_format: "%b. %e, %Y" # customize how date is formatted
  
   # This disables the "Description" at the top of the home page. Instead, I'll write the content for this page in Index.md.
  show_description: false

  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer

  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml

  # Details of blog posts
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: true # show tags in a blog posts

  # options for "home" page
  home:
    title_projects: My Work
    # title_misc_list: Details
    title_blog: Blog
    title_old_projects: Older Projects

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag